name: chicago
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - python=3.10
  - boto3
  - jupyter
  - notebook
  - numpy
  - pandas
  - plotly
  - pyspark
  - python-dotenv
  - scikit-learn
  - statsmodels
  - tensorflow
  - scipy
  - pyarrow
  - h3
  - hdbscan
  - holidays
  - pytest
  - streamlit
  - pip
  - pip:
    - streamlit-plotly-events
